---
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.2
    hooks:
      - id: pylint
        language_version: python3
        exclude: doc/convert_samples.py|doc/conf.py|versioneer.py|khiops/_version.py|setup.py
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.12.0
    hooks:
      - id: yamlfix
        exclude: packaging/conda/(meta|conda_build_config).yaml
  - repo: local
    hooks:
      - id: samples-generation
        name: samples-generation
        entry: bash doc/convert-samples-hook
        language: system
        files: khiops/samples/samples.py|khiops/samples/samples_sklearn.py
        pass_filenames: false
