---
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.5
    hooks:
      - id: pylint
        language_version: python3
        exclude: doc/convert_samples.py|doc/conf.py|versioneer.py|pykhiops/_version.py|setup.py
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.13.0
    hooks:
      - id: yamlfix
        exclude: packaging/conda/(meta|conda_build_config).yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.2
    hooks:
      - id: check-github-workflows
        args: [--verbose]
      - id: check-github-actions
        args: [--verbose]
  - repo: local
    hooks:
      - id: samples-generation
        name: samples-generation
        entry: bash doc/convert-samples-hook
        language: system
        files: pykhiops/samples/samples.py|pykhiops/samples/samples_sklearn.py
        pass_filenames: false
