---
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.5
    hooks:
      - id: pylint
        language_version: python3
        exclude: doc/convert_samples.py|doc/conf.py|versioneer.py|khiops/_version.py|setup.py
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3
        exclude: khiops/samples/samples.py|khiops/samples/samples_sklearn.py
      - id: isort
        alias: isort-samples
        name: isort-samples
        language_version: python3
        files: khiops/samples/samples.py|khiops/samples/samples_sklearn.py
        args: [--no-sections]
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.17.0
    hooks:
      - id: yamlfix
        exclude: packaging/conda/meta.yaml
        language: python
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.0
    hooks:
      - id: check-github-workflows
        args: [--verbose]
      - id: check-github-actions
        args: [--verbose]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: samples-generation
        name: samples-generation
        entry: bash doc/convert-samples-hook
        language: system
        files: khiops/samples/samples.py|khiops/samples/samples_sklearn.py
        pass_filenames: false
