{% set metadata = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}
package:
  name: {{ metadata.get('name') }}
  # The Conda version cannot contain the '-' character, so we eliminate it
  version: {{ metadata.get('version') | replace('-', '') }}

source:
  path: ../../

build:
  number: 0
  noarch: python
  entry_points:
    - kh-status = khiops.tools:kh_status_entry_point
    - kh-samples = khiops.tools:kh_samples_entry_point
    - kh-download-datasets = khiops.tools:kh_download_datasets_entry_point
    - pk-status = khiops.tools:pk_status_entry_point   # deprecated
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv

requirements:
  build:
    - python
    - setuptools
  host:
    - python
  run:
    - python
    - khiops-core =11.0.0b.0
    - pandas >=0.25.3
    - scikit-learn >=0.22.2
  run_constrained:
    # do not necessary use the latest version
    # to avoid undesired breaking changes
    - boto3 >=1.17.39,<=1.35.69
    - google-cloud-storage >=1.37.0
    # an open issue on boto3 (https://github.com/boto/boto3/issues/3585) forces a min version of pyopenssl
    - pyopenssl>=24.0.0,<25.0.0

outputs:
  - name: {{ metadata.get('name') }}
    test:
      commands:
        - kh-status
      imports:
        - khiops.core.api
        - khiops.sklearn.estimators

about:
  home: https://khiops.org
  license: BSD+3-clause
  license_file: LICENSE.md
  summary: Khiops is an AutoML suite for supervised and unsupervised learning
  doc_url: https://khiopsml.github.com/khiops-python
  dev_url: https://github.com/khiopsml/khiops-python
