{% set metadata = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}
package:
  name: {{ metadata.get('name') }}
  version: {{ metadata.get('version') }}

source:
  path: ../../

build:
  script_env:
    - KHIOPS_REVISION
    # Variables for signing the MODL executables in osx-arm64
    - KHIOPS_APPLE_CERTIFICATE_BASE64      # [osx and arm64]
    - KHIOPS_APPLE_CERTIFICATE_PASSWORD    # [osx and arm64]
    - KHIOPS_APPLE_CERTIFICATE_COMMON_NAME # [osx and arm64]
    - KHIOPS_APPLE_CERTIFICATE_ID          # [osx and arm64]
    - KHIOPS_APPLE_TMP_KEYCHAIN_PASSWORD   # [osx and arm64]
  entry_points:
    - kh-status = khiops.tools:kh_status_entry_point
    - kh-samples = khiops.tools:kh_samples_entry_point
    - kh-download-datasets = khiops.tools:kh_download_datasets_entry_point
    - pk-status = khiops.tools:pk_status_entry_point   # deprecated
  number: 0
  # Binary relocation of MODL and MODL_Coclustering is done in build.sh script
  # This is to be able to sign it, see the script for more details.
  binary_relocation:                     # [osx and arm64]
    - bin/kh-status                      # [osx and arm64]
    - bin/kh-samples                     # [osx and arm64]
    - bin/kh-download-datasets           # [osx and arm64]
    - bin/pk-status                      # [osx and arm64]
  detect_binary_files_with_prefix: false # [osx and arm64]

# Note on version pinning:
# OSX:
# - mpich=3.4.3 because 4.* is still unstable
# - requires conda-forge
# Linux:
# - mpich=4.0.3 because of bugs of the 3.* series
# - requires conda-forge
requirements:
  build:
    - mpich 4.0.3        # [linux]
    - mpich-mpicxx 4.0.3 # [linux]
    - mpich 3.4.3        # [osx]
    - mpich-mpicxx 3.4.3 # [osx]
    - msmpi              # [win]
    - cmake
    - ninja
    - python
    - setuptools
    - {{ compiler('cxx') }}
  host:
    - mpich 4.0.3        # [linux]
    - mpich-mpicxx 4.0.3 # [linux]
    - mpich 3.4.3        # [osx]
    - mpich-mpicxx 3.4.3 # [osx]
    - msmpi                # [win]
    - python
  run:
    - mpich 4.0.3   # [linux]
    - mpich 3.4.3   # [osx]
    - msmpi         # [win]
    - pandas >=0.25.3
    - python
    - scikit-learn >=0.22.2
  run_constrained:
    - boto3 >=1.17.39
    - google-cloud-storage >=1.37.0

outputs:
  - name: {{ metadata.get('name') }}
    test:
      commands:
        - MODL -v
        - MODL_Coclustering -v
        - kh-status
      imports:
        - khiops.core.api
        - khiops.sklearn.estimators

about:
  home: https://khiops.org
  license: BSD+3-clause
  license_file: LICENSE.md
  summary: Khiops is an AutoML suite for supervised and unsupervised learning
  doc_url: https://khiopsml.github.com/khiops-python
  dev_url: https://github.com/khiopsml/khiops-python
