#! /usr/bin/env bash
set -e

# Set the documentation and samples directories
DOC_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
SAMPLES_DIR="$DOC_DIR/../khiops/samples"

# Generate the rEST pages
python $DOC_DIR/convert_samples.py -f rst $SAMPLES_DIR $DOC_DIR/samples/samples.rst
python $DOC_DIR/convert_samples.py --sklearn -f rst $SAMPLES_DIR $DOC_DIR/samples/samples_sklearn.rst

# Generate the notebooks
python $DOC_DIR/convert_samples.py $SAMPLES_DIR $SAMPLES_DIR/samples.ipynb
python $DOC_DIR/convert_samples.py --sklearn $SAMPLES_DIR $SAMPLES_DIR/samples_sklearn.ipynb
