FROM ghcr.io/khiopsml/khiops/ubuntu22.04:latest
LABEL maintainer="136721202+popescu-v@users.noreply.github.com"
LABEL description="Contains a Khiops installation"

# Copy Khiops repo to the image local folder
COPY . .

#  Configure CMake
RUN true \
  && cmake -B ./khiops/build -S ./khiops -DCMAKE_BUILD_TYPE=Release -DMPI=ON -DTESTING=OFF -DBUILD_JARS=OFF -DCMAKE_INSTALL_PREFIX= \
  && true

# Build Khiops; add KNI to make cmake --install happy
RUN true \
  && cmake --build ./khiops/build --parallel --target MODL MODL_Coclustering KhiopsNativeInterface \
  && true

# Install MODL and MODL_Coclustering binaires to path
RUN true \
  && cmake --install ./khiops/build \
  && true

# Remove Khiops repo from the image
RUN true \
  && rm -fr ./khiops \
  && true

# Remove khiops-python repo from image
RUN true \
  && rm -fr ./khiops-python \
  && true

# Set mpich for default MPI
RUN true \
  && update-alternatives --set mpirun /usr/bin/mpirun.mpich \
  && true

# Check Khiops is accessible
RUN true \
  && khiops -v \
  && khiops_coclustering -v \
  && true

# Install Git (required for khiops-python version calculation) and Pip (required
# for setting up the Python environment of khiops-python)
RUN true \
  && apt-get -y update \
  && apt-get -y --no-install-recommends install git python3-pip \
  && rm -fr /var/lib/apt/lists/* \
  && apt-get clean \
  && true
