---
name: Build development container [PR]
on:
  pull_request:
    paths: [packaging/docker/khiopspydev/Dockerfile]
jobs:
  build-dev-container:
    permissions:
      packages: write
    uses: ./.github/workflows/build-dev-container.yml
