---
name: Build development container
env:
  DEFAULT_KHIOPS_REVISION: dev
  DEFAULT_KHIOPSDEV_OS: ubuntu22.04
on:
  workflow_dispatch:
    inputs:
      khiops-revision:
        default: dev
        description: Git tag, branch or commit of the Khiops repository
      khiopsdev-os:
        default: ubuntu22.04
        description: Github runner OS
  workflow_call:
    inputs:
      khiops-revision:
        type: string
        default: dev
        description: Git tag, branch or commit of the Khiops repository
      khiopsdev-os:
        type: string
        default: ubuntu22.04
        description: Github runner OS
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build-dev-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # to write in the Github package registry
    steps:
      - name: Checkout khiops-python sources
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          file: ./packaging/docker/khiopspydev/Dockerfile
          build-args: |
            "KHIOPS_REVISION=${{ inputs.khiops-revision }}"
            "KHIOPSDEV_OS=${{ inputs.khiopsdev-os }}"
          tags: ghcr.io/khiopsml/khiops-python/khiopspydev-${{ inputs.khiopsdev-os }}:latest
          push: true
      - name: Display the image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  test-dev-container:
    needs: build-dev-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/khiopsml/khiops-python/khiopspydev-${{ inputs.khiopsdev-os }}:latest
    steps:
      - name: Check Khiops executables
        run: |-
          khiops -v
          khiops_coclustering -v
