---
name: Build Ubuntu Khiops container
on:
  workflow_dispatch:
jobs:
  build-container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # Allows to write on the package registry
    permissions:
      packages: write
    steps:
      # Get current repo sources so that one can use the Dockerfile
      # in the 'docker/build-push-action' action
      - name: Checkout khiops-python sources
        uses: actions/checkout@v3
        with:
          ref: 92-add-workflows-for-automatic-testing  # XXX To remove before merge to dev
          path: khiops-python
      - name: Check out Khiops repo
        if: success() || failure()
        uses: actions/checkout@v3
        with:
          repository: khiopsml/khiops
          token: ${{ secrets.GITHUB_TOKEN }}
          path: khiops
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
        # relative path to the place where source code with Dockerfile is located
          context: .
          file: ./khiops-python/packaging/docker/Dockerfile.khiopspydev-ubuntu22.04
        # Note: Tags have to be all lower-case
          tags: ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:latest
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
