---
name: Build Pip Package
on:
  workflow_dispatch:
  push:
jobs:
  build-and-test-pip-package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          # Get Git tags so that versioneer can function correctly
          # See issue https://github.com/actions/checkout/issues/701
          fetch-depth: 0
      - name: Checkout Khiops samples
        if: success() || failure()
        uses: actions/checkout@v3
        with:
          repository: khiopsml/khiops-samples
          ref: v10.1.1
          token: ${{ secrets.GITHUB_TOKEN }}
          path: khiops-samples
      - name: Move Khiops samples where they are expected
        run: |
          mkdir -p /opt/khiops
          mv khiops-samples /opt/khiops/samples
      - name: Build and Install Pip Package
        run: |
          # This is needed so that the Git tag is parsed and the khiops-python
          # version is retrieved
          git config --global --add safe.directory $(realpath .)
          python3 setup.py sdist --dist-dir=./test_dist
          pip install $(ls ./test_dist/*.tar.gz)
      - name: Test Pip package
        run: |-
          PYKHIOPS_LOCATION=$(pip show pykhiops | awk '/^Location:/ { print $2 }')
          (cd ./test_dist && python3 $PYKHIOPS_LOCATION/pykhiops/samples/samples.py -i train_predictor -e)
          (cd ./test_dist && python3 $PYKHIOPS_LOCATION/pykhiops/samples/samples_sklearn.py -i khiops_classifier -e)
