---
name: Build (and deploy) API docs to GH Pages
on:
  push:
    tags: [v*]
  workflow_dispatch:
  pull_request:
    paths:
      - doc/**.rst
      - doc/create-doc
      - doc/clean-doc
      - doc/*.py
      - khiops/**.py
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  packages: read
  pages: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest
# queued. However, do NOT cancel in-progress runs as we want to allow these production deployments
# to complete.
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  create-docs:
    name: Create Sphinx docs
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:latest
      # Use the 'runner' user (1001) from github so checkout actions work properly
      # https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      options: --user 1001
    steps:
      - name: Checkout khiops-python
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: Checkout khiops-python-tutorial
        uses: actions/checkout@v4.1.0
        with:
          repository: khiopsml/khiops-python-tutorial
          path: doc/khiops-python-tutorial
      - name: Add pip scripts directory to path
        run: echo PATH="$PATH:/github/home/.local/bin" >> "$GITHUB_ENV"
      - name: Install doc build requirements
        run: |
          # Install package itself to install the samples datasets
          pip3 install .
          kh-download-datasets --force-overwrite
          kh-status

          # Install the doc python requirements
          cd doc
          pip3 install -U -r requirements.txt
      - name: Obtain Sphinx dependencies
        run: |
      - name: Build Sphinx Documentation
        run: |
          cd doc
          ./create-doc -t
      - name: Upload the docs as an artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: khiops-python-docs
          path: doc/_build/html/
  upload-docs:
    name: Upload docs to GH pages
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: create-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: khiops-python-docs
          path: kp-docs
      - name: Upload docsas pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: kp-docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
