---
name: Integration Tests
env:
  DEFAULT_SAMPLES_REVISION: main
on:
  workflow_dispatch:
    inputs:
      samples-revision:
        default: main
        description: Git tag, branch or commit for the khiops-samples repository
      run-long-tests:
        type: boolean
        required: false
        default: false
        description: Execute long tests
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test-access-to-remote-files:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/khiopsml/khiops-python/khiopspydev-ubuntu22.04:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged  # as docker will run inside the container we need this option otherwise docker would not start
    permissions:
      id-token: write
      contents: read
      checks: write
      packages: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          # Get Git tags so that versioneer can function correctly
          # See issue https://github.com/actions/checkout/issues/701
          fetch-depth: 0
      - name: Install khiops-python dev dependencies
        run: |
          # The following git command is required, 
          # as the Git repository is in a directory the current user does not own,
          # Python versioneer fails to compute the current version correctly otherwise
          git config --global --add safe.directory $(realpath .)
          python setup.py egg_info
          pip install `grep -v "^\[" khiops.egg-info/requires.txt`
          rm -rf khiops.egg-info
      - name: Setup and Install Test Requirements
        run: |
          pip install -r test-requirements.txt
          pip install unittest-xml-reporting
      - name: Launch the tests
        env:
          # for the tests with GCS
          GCS_BUCKET_NAME: gcs-bucket
          STORAGE_EMULATOR_HOST: http://localhost:4443
          # for the tests with S3
          S3_BUCKET_NAME: s3-bucket
          AWS_SECRET_ACCESS_KEY: XXX
          AWS_ENDPOINT_URL: http://localhost:4569
          AWS_ACCESS_KEY_ID: XXX
          # common vars
          # Force > 2 CPU cores to launch mpiexec
          KHIOPS_PROC_NUMBER: 4
        run: |-
          /scripts/run_fake_remote_file_servers.sh  # launch the servers in the background
          python -m xmlrunner tests.test_remote_access.KhiopsGCSRemoteFileTests -o reports/
          python -m xmlrunner tests.test_remote_access.KhiopsS3RemoteFileTests -o reports/
      - name: Display Integration Test Reports
        uses: dorny/test-reporter@v1
        with:
          name: Integration Tests
          path: >-
            reports/TEST-tests.test_remote_access.*.xml,
          reporter: java-junit
          path-replace-backslashes: 'true'  # Necessary for windows paths
      - name: Upload Test Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-reports
          path: |-
            reports/TEST-tests.test_remote_access.*.xml
            test/resources/tmp/khiops-cicd/*/*
            tests/resources/scenario_generation/*/ref/*._kh
            tests/resources/scenario_generation/*/output/*._kh
            tests/resources/*/output_reports/*.txt
            tests/resources/*/ref_reports/*.txt
            tests/resources/dictionary/ref_kdic/*.kdic
            tests/resources/dictionary/output_kdic/*.kdic
            tests/resources/dictionary/copy_output_kdic/*.kdic
            tests/resources/general_options/general_options/*/*._kh
          retention-days: 7
