---
name: Run pre-commit checks
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install khiops-python dependencies
        run: |
          # Extract and install package dependency requirements from metadata
          pip install pip-tools
          python -m piptools compile -o requirements.txt
          pip install -r requirements.txt
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
