---
name: Quick Checks
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install khiops-python dev dependencies
        run: |
          # Extract and install package dependency requirements from metadata
          pip install pip-tools
          python -m piptools compile -o requirements.txt

          # Install dev dependencies
          pip install -r requirements.txt

          # Install black for the samples-generation script
          pip install black
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
